2024-08-03 13:55:49,310 INFO    MainThread:103480 [wandb_setup.py:_flush():68] Configure stats pid to 103480
2024-08-03 13:55:49,310 INFO    MainThread:103480 [wandb_setup.py:_flush():68] Loading settings from /home/anna_y/.config/wandb/settings
2024-08-03 13:55:49,310 INFO    MainThread:103480 [wandb_setup.py:_flush():68] Loading settings from /home/anna_y/PINNACLE/pinnacle/wandb/settings
2024-08-03 13:55:49,310 INFO    MainThread:103480 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-08-03 13:55:49,310 INFO    MainThread:103480 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'pinnacle/train.py', 'program': 'train.py'}
2024-08-03 13:55:49,311 INFO    MainThread:103480 [wandb_init.py:_log_setup():476] Logging user logs to /home/anna_y/PINNACLE/pinnacle/wandb/run-20240803_135549-2nm0zehi/logs/debug.log
2024-08-03 13:55:49,311 INFO    MainThread:103480 [wandb_init.py:_log_setup():477] Logging internal logs to /home/anna_y/PINNACLE/pinnacle/wandb/run-20240803_135549-2nm0zehi/logs/debug-internal.log
2024-08-03 13:55:49,312 INFO    MainThread:103480 [wandb_init.py:init():516] calling init triggers
2024-08-03 13:55:49,312 INFO    MainThread:103480 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'pc_att_channels': 16, 'feat_mat': 1024, 'output': 16, 'hidden': 64, 'lr': 0.01, 'wd': 1e-05, 'dropout': 0.6, 'gradclip': 1.0, 'n_heads': 8, 'lambda': 0.1, 'theta': 0.3, 'lr_cent': 0.1, 'loss_type': 'BCE', 'plot': False}
2024-08-03 13:55:49,313 INFO    MainThread:103480 [wandb_init.py:init():569] starting backend
2024-08-03 13:55:49,313 INFO    MainThread:103480 [wandb_init.py:init():573] setting up manager
2024-08-03 13:55:49,324 INFO    MainThread:103480 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-08-03 13:55:49,335 INFO    MainThread:103480 [wandb_init.py:init():580] backend started and connected
2024-08-03 13:55:49,349 INFO    MainThread:103480 [wandb_init.py:init():658] updated telemetry
2024-08-03 13:55:49,399 INFO    MainThread:103480 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2024-08-03 13:55:56,549 WARNING MsgRouterThr:103480 [router.py:message_loop():77] message_loop has been closed
2024-08-03 13:56:04,424 ERROR   MainThread:103480 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/anna_y/.conda/envs/pinnacle/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/anna_y/.conda/envs/pinnacle/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/anna_y/.conda/envs/pinnacle/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
